paths:
  background: /mnt/fscompute_shared/simulation_dataset/backgrounds
  events: /mnt/fscompute_shared/simulation_dataset/events
  output: /mnt/fscompute_shared/simulation_dataset/outputs
  masks: /mnt/fscompute_shared/simulation_dataset/masks
  denoised: /mnt/fscompute_shared/simulation_dataset/denoised_tuned
  filters: /mnt/fscompute_shared/simulation_dataset/filters
  datasets: /mnt/fscompute_shared/simulation_dataset/datasets

dataset:
  samplerate: 48000
  duration: 10
  snr_values: [-25, -20, -15, -10, -5, 0, 5, 10, 15, 20]
  num_files_per_snr: 100
  num_events_per_file: [0,1]
  num_workers: 12
  dataframe_name: 20260319_dataset.pkl
  denoise_processes: 12
  Xi: 0.20 # og was 1e-4
  beta: 0.97 #og was 0.92
